// src/services/rag/types.ts



export type RAGMode = 'simple' | 'advanced';
export type UseCaseProfile = 'GENERAL_QA' | 'TECHNICAL_DOCUMENTATION' | 'COMPANY_POLICY' | 'DATABASE_KNOWLEDGE' | 'CUSTOM';
export type ParserType = 'auto' | 'native' | 'markitdown';
export type ChunkStrategy = 'recursive' | 'section' | 'fixed';
export type RetrievalMode = 'vector' | 'keyword' | 'hybrid' | 'adaptive';
export type CitationMode = 'none' | 'inline' | 'source_list';
export type RerankerProvider = 'none' | 'local_cross_encoder' | 'simple_lexical' | 'cohere';

export interface RAGConfiguration {
  mode: RAGMode;
  useCaseProfile: UseCaseProfile;
  ingestion: {
    parser: ParserType;
    chunkSize: number;
    chunkOverlap: number;
    chunkStrategy: ChunkStrategy;
  };
  retrieval: {
    mode: RetrievalMode;
    topK: number;
    vectorWeight: number;
    keywordWeight: number;
    minScore: number;
  };
  reranker: {
    provider: RerankerProvider;
    topN: number;
    minScore?:number;
  };
  context: {
    strategy: 'top_chunks' | 'parent_child' | 'neighbors';
    maxTokens: number;
    citationMode: CitationMode;
  };
  generation: {
    enabled: boolean;
    provider: 'gemini';
    model: string;
    temperature: number;
    systemPrompt: string;
  };
}

export interface IngestionInput {
  name: string;
  mimeType: string;
  source: string; // Original filepath or content URL
  contentBuffer?: Buffer; // File buffer loaded in memory
}

export interface ParsedChunk {
  content: string;
  embedding?: number[]; // Vector array of floats generated by bge-m3
  metadata: Record<string, string>;
}

export interface NormalizedDocument {
  title: string;
  rawContent: string;
  normalizedContent: string;
  chunks: ParsedChunk[];
}

export interface DocumentParser {
  canParse(mimeType: string): boolean;
  parse(input: IngestionInput, options: { chunkSize: number; chunkOverlap: number }): Promise<NormalizedDocument>;
}

export interface RetrievalResult {
  chunkId: string;
  documentId: string;
  content: string;
  score: number;
  retrievalMethod: RetrievalMode;
  metadata: Record<string, any>;
  source: string;
  title: string;
  initialRank?:number // Pre-rerank position in the candidate list
}

export interface QueryAnalysis {
  originalQuery: string;
  normalizedQuery: string;
  intent: string;
  keywords: string[];
  filters: Record<string, string>;
}

export interface RetrievalPlan {
  strategies: RetrievalMode[];
  topK: number;
  metadataFilters: Record<string, string>;
  vectorWeight: number;
  keywordWeight: number;
  minScore: number;
}


export interface RerankOptions {
  topN: number;
  minScore?: number;
}

export interface IReranker{
  rerank(query:string , candidates:RetrievalResult[] , options:RerankOptions):Promise<RetrievalResult[]>;
}